server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nonamedb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
        #pool:
      #最大连接数(负数表示没有限制)
       # max-active: 100
      #最大空闲连接
          #max-idle: 10
      #最大阻塞等待时间(负数表示没有限制)
         # max-wait: 100000
    #连接超时时间(毫秒)
      #  timeout: 2000
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.noname.demo.entity
logging:
  level:
    com:
      example:
        mapper : debug
